graph TD
  Start((📍 Oggi)) --> DigIn1["🛠 Dati & Privacy 1.3"]
  DigIn1 --> DigIn2[""🛠 AI 1.3"]
  DigIn2 --> DigIn3["🕒 Tecnologia nella Società 1.3"]
  DigIn3 --> D3P["🛠️ Avvio D3P"]
  D3P --> D3PTest["📱 Test su smartphone"]
  D3P --> ItHub["🧩 Prototipo ItHub"]
  ItHub --> HubLoc["📍 Stanze Locali"]
  ItHub --> SPID["🛡️ Accesso Etico"]
